### ISSUE TITLE
The included agent AI gets stuck when trying to leave a shop

### ISSUE THREAD

**Issue by houeland** [ForgottenArbiter/spirecomm#1] opened 2019-10-22 01:33 UTC
When running the AI, the game currently gets stuck for me when the agent has completed shopping and is trying to leave a merchant store.

Manually leaving the store allows the agent to continue and it can complete the other parts of the run.

**Comment by houeland** [comment] 2019-10-26 16:37
From running the AI some more, it looks the problem is in CommunicationMod not performing the leave/cancel correctly, and it looks like the problem does *not* trigger when some actions are made instant by SuperFastMode.

So this might e.g. be a race condition where the cancel command is sent and attempted to be triggered by CommunicationMod before the game actually accepts it.

**Comment by ForgottenArbiter** [comment] 2019-11-06 08:37
I haven't been able to reproduce this behavior with Communication Mod, unfortunately. I believe someone else also reported the same issue to me a few months ago, but neither of us were able to figure it out then, either.

Likely, Communication Mod has received the command to leave the shop and attempted to execute it. However, somehow leaving the shop did not work, so because the game state has not changed, no message is ever sent back to the AI, and it waits patiently. The problem would be on the end of Communication Mod here. It may be sensible to make commands "time out" in case they do not produce a state change for whatever reason.

**Comment by ForgottenArbiter** [comment] 2020-05-20 08:55
I believe this is now fixed in Communication Mod 1.0.1.

**Closed as completed by ForgottenArbiter** 2020-05-20 08:55 UTC
